### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [yassirh/digitalocean-swimmer#73]
Hi @yassirh 

I found [this app](https://play.google.com/store/apps/details?id=com.Magenta.digitalocean) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

By the way, [all his apps are open source software he copied](https://play.google.com/store/apps/developer?id=Vu+Viet+My+Team)...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by yassirh** [comment]
Hello @Poussinou 

I am not sure it is really a copyright violation because this project's licence is MIT. So basically any one can do whatever they wish (From the MIT licence : the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software). The only thing that is missing is a link to the licence.

Obviously, I don't like how he/she is doing this. I also believe his/her downloads are fake because his app is ranked so low in the search that he can't get any chance to get downloads.

I will look into reporting it. So thank you for the time and the effort! I will keep you posted.
